### ISSUE TITLE
Tag results combine as AND rather than OR

### ISSUE THREAD

**Issue by IdiosApps** [espanso/hub-frontend#19]
Expected behaviour:

When I
- Click "Jokes" tag (there is 1 package with this tag)
- Click "Turkish" tag (there is 1 package with this tag)
Then
- I see 2 results

Currently
- I see 0 results

Given that there's not too many packages, I think OR is more helpful to help people find more packages to try out.
I'd suggest sorting the results by the most tag matches.

Feel free to close the issue if you think it behaves as expected too - that's fair :)
If it sounds good, I could give it a go and learn some React :)

**Comment by arabello** [comment]
Hi! Thank you for reporting this. I would say that the current behaviour is not the expected one: it is a bug. 
The root problem is [here](https://github.com/espanso/hub-frontend/blob/main/api/search.ts#L20-L28):
```
export const tagsSearch: (
  packages: Array<Package>
) => (tags: NonEmptyArray<string>) => Array<Package> = (packages) => (tags) =>
  pipe(
    tags,
    array.reduce(packages, (acc, tag) =>
      acc.filter((p) => p.tags.includes(tag))
    )
  );
```
which is actually filtering the packages per each tag sequentially. It should be converted to an `AND` logic equivalent.

Feel free to give it a try if you would like to! Otherwise I'll be happy to fix it.

**Comment by IdiosApps** [comment]
@arabello Thanks for the intro. I will have a try at this with TDD 😺

**Comment by IdiosApps** [comment]
@arabello I had a go and learnt a bit about fp-ts, and managed to learn I can do Package.Decode{packageJson}) to get an Either (fortunately, a right - by following semver to make that decoder happy!). I'm a bit stuck trying to collect these and extract the values from the Either, so I can make the array and pass it to the tagsSearch function you linked.

I might need a little help to make the PR. I've emailed you my contact details in case you prefer to talk over Discord or so.

**Comment by arabello** [comment]
Hi @IdiosApps, that's great! Thanks!

I'm not sure to understand your approach as decoding the packages JSON shouldn't be required. I think I wasn't clear on my initial analysis (sorry about that): `tagsSearch` filters the packages based on the given `tags` argument. The problem is its implementation because it is sequentially filtering per each tag (AND logic).  It should be sufficient to edit the `tagsSearch`'s internal logic, no need to invoke it with different values. How were you planning to address it?

By the way, I added you on Discord. Feel free to DM me and have a talk!

**Comment by IdiosApps** [comment]
PR raised https://github.com/espanso/hub-frontend/pull/21
Thanks for all your help @arabello !
