### ISSUE TITLE
Typofixer-fr package on Espanso Hub contains the english file

### ISSUE THREAD

**Issue by viviengarcia** [espanso/hub-frontend#51]
Pretty self-explanatory… On [Espanso Hub](https://hub.espanso.org/typofixer-fr), the source file is not the good one.

**Comment by Mte90** [comment]
Done https://github.com/espanso/hub-frontend/issues/51

**Comment by smeech** [comment]
Thanks - it's corrected in https://github.com/espanso/hub/blob/main/packages/typofixer-fr/1.0.1/package.yml but it may take a while for the Hub to pick it up for installation by from the command line.

If it hasn't done so in a few days, we'll need to ask @arabello to trigger a reindex.

**Comment by arabello** [comment]
Interesting: the CI [triggered and built](https://github.com/espanso/hub-frontend/actions/runs/11892492748/job/33135459834) the hub after the PR merge. However, I currently see the following behavior:
- `https://hub.espanso.org/typofixer-fr` => `typofixer-en`
- `https://hub.espanso.org/typofixer-fr/v/1.0.0` => `typofixer-fr`
- `https://hub.espanso.org/typofixer-fr/v/1.0.1` => `typofixer-fr`

weird because `/typofixer-fr/v/1.0.1` should be the fallback for `/typofixer-fr` as latest version

We might found a bug

**Comment by viviengarcia** [comment]
> Well spotted! Sorry, I didn't see this when you originally posted (I check https://github.com/espanso/hub/issues more frequently).

It's alright! ^^

THanks @Mte90 @smeech @arabello for your efforts, really appreciated!

**Comment by smeech** [comment]
> Interesting: the CI [triggered and built](https://github.com/espanso/hub-frontend/actions/runs/11892492748/job/33135459834) the hub after the PR merge. However, I currently see the following behavior:
> 
> * `https://hub.espanso.org/typofixer-fr` => `typofixer-en`
> * `https://hub.espanso.org/typofixer-fr/v/1.0.0` => `typofixer-fr`
> * `https://hub.espanso.org/typofixer-fr/v/1.0.1` => `typofixer-fr`
> 
> weird because `/typofixer-fr/v/1.0.1` should be the fallback for `/typofixer-fr` as latest version
> 
> We might found a bug

It all seems OK now. @arabello, would you like to close the Issue? I don't have the permissions here.

**Comment by smeech** [comment]
Thank you.
